[routing]
init_behaviour = "fmt.Printf(\"Starting webserver at port 8080\")"
fail_behaviour = "log.Fatal(err)"
imports = ["fmt", "log"]

[misc]
latex = true # Add KaTeX support
html_lang = "en" # HTML Language
syntax_highlighting = true

[config]
# Add any custom templates here!
